# Generated by Django 5.0.1 on 2024-01-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1_card_num', models.IntegerField(default=0)),
                ('user_2_card_num', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('rule', models.CharField(choices=[('bigger', '큰 숫자가 이기는 룰'), ('smaller', '작은 숫자가 이기는 룰')], default=('smaller', '작은 숫자가 이기는 룰'), max_length=10)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1_games', to='games.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2_games', to='games.user')),
            ],
        ),
    ]
