# Generated by Django 5.0.1 on 2024-01-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_games', to='games.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_games', to='games.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rule',
            field=models.CharField(choices=[('bigger', '큰 숫자가 이기는 룰'), ('smaller', '작은 숫자가 이기는 룰')], default=('bigger', '큰 숫자가 이기는 룰'), max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='games.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenders', to='games.user'),
        ),
    ]
