# Generated by Django 5.0.1 on 2024-01-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_1_card_num',
            field=models.IntegerField(choices=[(1, '1'), (4, '4'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2_card_num',
            field=models.IntegerField(choices=[(1, '1'), (4, '4'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
    ]
