# Generated by Django 5.0.1 on 2024-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rule',
            field=models.CharField(choices=[('bigger', '큰 숫자가 이기는 룰'), ('smaller', '작은 숫자가 이기는 룰')], default=('bigger', '큰 숫자가 이기는 룰'), max_length=10),
        ),
    ]
