# Generated by Django 5.0.1 on 2024-01-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_user_1_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_1_card_num',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (4, '4'), (6, '6'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2_card_num',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (7, '7'), (10, '10')], default=0),
        ),
    ]
