# Generated by Django 5.0.1 on 2024-01-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_user_1_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_1_card_num',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (7, '7'), (8, '8')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2_card_num',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (10, '10')], default=0),
        ),
    ]
