# Generated by Django 5.0.1 on 2024-01-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_user_1_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_1_card_num',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2_card_num',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (9, '9'), (10, '10')], default=0),
        ),
    ]
